# Generated by Django 3.0.5 on 2021-07-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_auto_20210710_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
