# Generated by Django 3.0.5 on 2021-07-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_remove_shippingaddress_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Country',
            new_name='country',
        ),
    ]
