# Generated by Django 3.0.5 on 2021-07-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_orderitem_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='address',
        ),
    ]
