# Generated by Django 3.0.5 on 2021-07-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_remove_orderitem_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
